#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2025 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
prepare_service 20-argus
SERVICE_NAME="argus-config-reload"

check_container_initialized
check_service_initialized 20-argus
liftoff

if var_true "${RESTART_ON_CONFIG_CHANGE}" ; then
    CONTAINER_PROCESS_RUNAWAY_LIMIT=32767
fi

while inotifywait -q -e modify "${CONFIG_PATH}"/"${CONFIG_FILE}" >/dev/null 2>&1 ; do
  print_info "Restarting Argus due to a detected configuration file change"
  pkill argus
  exit 0
done
