services:
  argus-app:
    image: docker.io/nfrastack/argus:latest
    container_name: argus-app
    labels:
    labels:
      - traefik.enable=true
      - traefik.http.routers.argus-app.rule=Host(`argus.example.com`)
      - traefik.http.services.argus-app.loadbalancer.server.port=80
    volumes:
      - ./config:/config
      - ./data:/data
      - ./logs/argus:/logs/
      - ./logs/nginx:/www/nginx/
    environment:
      - TIMEZONE=America/Vancouver

      - SETUP_TYPE=AUTO
    networks:
      - proxy
      - services
    restart: always

networks:
  proxy:
    external: true
  services:
    external: true
